[package]
name = "nots_dynamic_dns"
version = "0.1.0"
authors = ["Jacob Kauffmann <jacob@nerdonthestreet.com>"]
edition = "2021"

[dependencies]
reqwest = { version = "0.11.6", features = ["blocking", "json"] }
tokio = { version = "1.13.0", features = ["full"] }
serde_json = "1.0.68"
